### ISSUE TITLE
Fix dependency

### ISSUE THREAD

**Issue by xaronnn** [Favna/sapphire-sample-bot#1]
![image](https://user-images.githubusercontent.com/28219912/125196153-65a5c580-e261-11eb-9f7c-fc23ad4b728e.png)

**Comment by Favna** [comment]
While yes this is an issue in the code, it should be noted that this project has been bootstrap with yarn (see: `yarn.lock` file) and this is exclusively a problem with NPM v7, not with Yarn v1. Furthermore, the fix is listed right in your screenshot:

![image](https://user-images.githubusercontent.com/4019718/125207285-ae727400-e28b-11eb-93cf-8f9d79c15941.png)
